---
- name: Setup Lab Environment
  hosts: localhost
  become: true
  tasks:
    - name: Hostname
      ansible.builtin.command: hostname
      register: hostname

    - name: Output Hostname
      debug:
        var: hostname.stdout 