---
- name: Setup Management Environment
  hosts: localhost
  become: true
  vars:
    zsh_antigen_bundles_extras:
      - nvm
      - joel-porquet/zsh-dircolors-solarized
    zsh_autosuggestions_bind_key: "^U"
  roles:
    - { role: viasite-ansible.zsh, zsh_user: zhaho }
  tasks:
    - name: Hostname
      ansible.builtin.command: hostname
      register: hostname

    - name: Output Hostname
      debug:
        var: hostname.stdout