---
- name: Setup Management Environment
  hosts: localhost
  become: true

  tasks:
    - name: Ensure required role is installed
      ansible.builtin.shell: |
        ansible-galaxy install viasite-ansible.zsh --force
      args:
        executable: /bin/bash
      changed_when: false

    - name: Reload Ansible roles path
      ansible.builtin.meta: reset_connection  # Ensures Ansible picks up newly installed roles

---
- name: Install ZSH
  hosts: localhost
  become: true
  vars:
    zsh_antigen_bundles_extras:
      - nvm
      - joel-porquet/zsh-dircolors-solarized
    zsh_autosuggestions_bind_key: "^U"
  roles:
    - { role: viasite-ansible.zsh, zsh_user: zhaho }
  