---
- name: Setup ZSH
  hosts: localhost
  become: true
  vars:
    zsh_antigen_bundles_extras:
      - nvm
      - joel-porquet/zsh-dircolors-solarized
    zsh_autosuggestions_bind_key: "^U"
  roles:
    - role: viasite-ansible.zsh
      zsh_user: "{{ host_user }}"