---
- name: Setup Oh mY Posh
  hosts: localhost
  become: true
  vars:
    omz_install_zsh: true
    users:
      - name: "{{ host_user }}"
        group: "{{ host_user }}"
        settings: ""
  tasks:
    - name: Run ansible-role-oh-my-zsh.
      include_role:
        name: "ansible-role-oh-my-zsh"
      vars:
        omz_user: "{{ item }}"
        omz_zshrc_create: true
        omz_theme: "obraun"
        omz_plugins:
          - "autojump"
          - "git"
      with_items: "{{ users }}"
