---
- name: Install APT Packages Locally
  hosts: localhost
  become: true
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required APT packages
      ansible.builtin.apt:
        name:
          - vim
          - htop
          - net-tools
        state: present
